export const data = {
  blocks: [
    {
      component: "VText",
      label: "文本",
      propValue: "我是文本",
      icon: "wenben",
      animations: [],
      events: {},
      style: {
        display: 'flex',
        width: 200,
        height: 28,
        fontSize: 20,
        fontWeight: 400,
        lineHeight: "",
        letterSpacing: 0,
        justifyContent: "flex-start",
        color: "",
      },
    },
    {
      component: 'RectShape',
      label: '矩形',
      propValue: '',
      icon: 'juxing',
      animations: [],
      events: {},
      style: {
          display: 'flex',
          width: 200,
          height: 200,
          paddingLeft: 20,
          paddingRight: 20,
          paddingTop: 20,
          paddingBottom: 20,
          fontSize: '',
          fontWeight: 400,
          lineHeight: 20,
          letterSpacing: 0,
          justifyContent: 'center',
          color: '',
          borderColor: '#000',
          borderWidth: 1,
          backgroundColor: '',
          borderStyle: 'solid',
          borderRadius: '',
          alignItems: 'center',
          boxSizing: 'border-box',
      },
  },
  ],
};
